### PR TITLE
Update OpenStack project mappings

### PR DESCRIPTION
**Pull request by emonty**
The list of which projects are part of OpenStack and which are not is
maintained here:

  http://git.openstack.org/cgit/openstack/governance/tree/reference/projects.yaml

Repos listed there are "OpenStack" - repos that are not are not. All of the
things listed in there are considered to be part of "One Project", not a
collection of independent projects.

The hints file has been updated to reflect this.

There were also projects that are OpenStack related but not associated
with OpenStack's official developer community. Those have been updated
to indicate that they are individual efforts (for instance, the repos in
openstack-charmers is an independent effort and should be tracked as
such)

Will do a follow up with some BigQuery files to cover getting the git
and other data from Gerrit. (OpenStack doesn't use PRs, so numbers
tracked from BigQuery involving those thing are currently inaccurate
-but the data does exist, so we can get it up to date)

It's possible there are other files that should be updated with the
updated hints file, but I wasn't sure what was "right" there.

### CODE REVIEW

**Comment by lukaszgryglicki** [comment]
I'll review all mappings now and I will regenerate top projects using it.

**Comment by lukaszgryglicki** [comment]
I've fetched branch locally and run: `./shells/unlimited_20160601-20170601.sh` on it.
Branch is `lukaszgryglicki-check-pr-2`.

The problem is that LOT of repos are now in "OpenStack" (on `monthly:master` and  `lukaszgryglicki-check-pr-2` branches).
They should be on something like "OpenStack (other)" or "OpenStack (unmapped)".
So OpenStack it is becoming 1st or 2nd (this is something like we put all non-mapped GitHub repos into single project called "GitHub").

We decided not to sum all remaining repos into just "OpenStack" (that's why "OpenStack (other)" it was in map/skip.csv) so I think this we at least need to add "OpenStack" to skip list.

Also there is no OpenStack's Nova, Cinder, Neutron anymore. 
Not only in Top 30 but nowhere.
This is strange because those projects were mapped OK imho and they really are OpenStack's projects: see https://wiki.openstack.org/wiki/Bugs#Bugs_lifecycle
All those 14 projects were defined in mapping, and now they're gone.

All OpenStack related projects from new mapping:
```
[4] pry(main)> res.map.with_index { |e, i| [e, i] }.select { |e| e[0][0].match("/openstack/i".to_regexp) }.map { |e| "#{e[1]} #{e[0][0]}" }
=> ["1 OpenStack",
 "6 OpenStack Community",
 "14 OpenStack Infra",
 "627 redhat-openstack",
 "657 OpenStack (retired)",
 "6956 OpenStack Charms",
 "9417 emc-openstack",
 "9500 OpenStack Snaps",
 "9503 OpenStack Hyper-V",
 "13496 OpenStack Mobile",
 "14447 ruby-openstack",
 "14757 OpenStack Korean",
 "18452 ubuntu-openstack",
 "19634 openstack-ansible-galaxy",
 "23306 OpenStack NET SDK",
 "40696 twc-openstack"]
[5] pry(main)> res[1][2][:sum]['authors']
=> 3641
from (pry):6:in `analysis'
[7] pry(main)> res[6][2][:sum]['authors']
=> 1328
```

You can see 14 OpenStack projects are gone (from this list https://wiki.openstack.org/wiki/Bugs#Bugs_lifecycle):
```
Report a bug in Nova
Report a bug in Glance
Report a bug in Swift
Report a bug in Horizon
Report a bug in Keystone
Report a bug in Cinder
Report a bug in Neutron
Report a bug in Heat
Report a bug in Manila
Report a bug in Murano
Report a bug in Mistral
Report a bug in the manuals
Report a bug in the api documentation
Report a bug in the community tools
```

Anyway - created alternative chart with new mapping here: https://docs.google.com/spreadsheets/d/1NJu5rAmZYe-VcEO6Fl42TeoWzitAVfnMq3MtR3m5dyY/edit?usp=sharing

**Comment by hannibalhuang** [comment]
OpenStack does not rely on PRs or issues, so I'm curious on how OpenStack's gerrit review and bugs statistics mapped to the chart here ?

**Comment by lukaszgryglicki** [comment]
Issues are something like bugs.
Please Follow README.md and search for "- OpenStack case:"

**Comment by lukaszgryglicki** [comment]
Closing this as really outdated.

**Pull request closed without merging**
